import type { Metadata } from "next";

import { Providers } from "./Providers";
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  return (
    <html lang="en" className='light'>
      <body
        className={` antialiased transition-colors duration-500 ease-in-out bg-slate-50 dark:bg-[#2D3748] `}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
